version: 2

before:
  hooks:
    - bash -c "cd frontend && npm ci"
    - bash -c "cd frontend && npm run build"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    files:
      - README.md
      - LICENSE

dockers:
  - image_templates:
      - "ghcr.io/tokuhirom/dashyard:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
      - "ghcr.io/tokuhirom/dashyard:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/tokuhirom/dashyard:{{ .Version }}"
    image_templates:
      - "ghcr.io/tokuhirom/dashyard:{{ .Version }}-amd64"
      - "ghcr.io/tokuhirom/dashyard:{{ .Version }}-arm64"
  - name_template: "ghcr.io/tokuhirom/dashyard:latest"
    image_templates:
      - "ghcr.io/tokuhirom/dashyard:{{ .Version }}-amd64"
      - "ghcr.io/tokuhirom/dashyard:{{ .Version }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
